# An example of ClusterConfig object using an existing VPC:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS01-CLUSTER
  region: us-east-1

vpc:
  id: "vpc-084b65ae2cadc2e74"  # (optional, must match VPC ID used for each subnet below)
  cidr: "192.168.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      us-east-1a:
        id: "subnet-043fadbe6aea1890c"
        cidr: "192.168.64.0/18" # (optional, must match CIDR used by the given subnet)

      us-east-1b:
        id: "subnet-020335a17e8cb70ba"
        cidr: "192.168.128.0/18"  # (optional, must match CIDR used by the given subnet)

      us-east-1c:
        id: "subnet-0db56d6584870892b"
        cidr: "192.168.192.0/18"   # (optional, must match CIDR used by the given subnet)

nodeGroups:
  - name: EKS01-NG1
    instanceType: t2.medium
    desiredCapacity: 2
    privateNetworking: false # if only 'Private' subnets are given, this must be enabled
    ssh: # use existing EC2 key
      publicKeyName: eks-publickey
