apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::118143304519:role/eksctl-eks-k8s-cluster-nodegroup-NodeInstanceRole-1NKX78WWMHBVF
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::118143304519:user/eks-admin1
      username: eks-admin1
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::118143304519:role/eksctl-eks-k8s-cluster-nodegroup-NodeInstanceRole-1NKX78WWMHBVF\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::118143304519:user/eks-admin1\n  username: eks-admin1\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2019-12-01T13:08:24Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1593","selfLink":"/api/v1/namespaces/kube-system/configmaps/aws-auth","uid":"a837e1a3-143b-11ea-aae3-0a7e6c6ed5f3"}}
  creationTimestamp: "2019-12-01T13:08:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "30987"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a837e1a3-143b-11ea-aae3-0a7e6c6ed5f3
