kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: production-support
  name: prod-viewer-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]  # can be further limited, e.g. ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch"] 
