apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-k8s-cluster
  region: us-east-1
 # zones: ["us-east-1a","us-east-1b","us-east-1d"]
 #zones: us-east-1a,us-east-1b,us-east-1c

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh: # use existing EC2 key, ensure its available in the same account.
      publicKeyName: eks-publickey
  - name: ng-mixed
    minSize: 3
    maxSize: 5
    instancesDistribution:
      maxPrice: 0.2
      instanceTypes: ["t2.small", "t3.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
    ssh:
      publicKeyname: eks-publickey
